//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Movie
{
	public virtual List<Actor> Actorts
	{
		get;
		set;
	}

	public virtual int LengthInMinutes
	{
		get;
		set;
	}

	public virtual string Name
	{
		get;
		set;
	}

	public virtual DateTime ReleaseDate
	{
		get;
		set;
	}

	public virtual string Website
	{
		get;
		set;
	}

}

