//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class MovieFacade
{
	public virtual bool HasBeenPlayed
	{
		get;
		set;
	}

	public virtual void IsPlaying()
	{
		throw new System.NotImplementedException();
	}

}

