//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;

public class Netflix : IPlayer
{
	public virtual void PlayMovie(string movieName)
	{
        Debug.WriteLine("NETFLIX IS BEING PLAY");
	}

}

